version: '3.8'  # You may specify the version of Docker Compose you're using

services:
  client:
    build:
      context: ./BurgerOrderer
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  kitchen:
    build:
      context: ./KitchenView
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend

  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://user:BTHDonken@mysql:3306/burger_db
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: hamburger
      MYSQL_DATABASE: burger_db
      MYSQL_USER: user
      MYSQL_PASSWORD: BTHDonken
    ports:  # Corrected indentation
      - "3306:3306"  # Corrected indentation
    volumes:  # Corrected indentation
      - mysql-data:/var/lib/mysql  # Corrected indentation

volumes:
  mysql-data:
