# docker-compose.yml
services:
  client:
    build: ./client-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  kitchen:
    build: ./kitchen-frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/burger-db
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
