version: '3.8'

services:
  client:
    build:
      context: ./BurgerOrderer
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  kitchen:
    build:
      context: ./KitchenView
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend

  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://user:BTHDonken@mysql:3306/burger_db
    depends_on:
      mysql:
        condition: service_healthy
    restart: always 

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: hamburger
      MYSQL_DATABASE: burger_db
      MYSQL_USER: user
      MYSQL_PASSWORD: BTHDonken
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
